<?php

namespace Deporte\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DatDepmodmarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatDepmodmarRepository extends EntityRepository
{
}
