<?php

namespace Deporte\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DatMedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatMedRepository extends EntityRepository
{
}
