<?php

namespace Deporte\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TipoEscuelaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoEscuelaRepository extends EntityRepository
{
}
